version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel.project
      - pgsql
    networks:
      - laravel
  pgsql:
    image: 'postgres:14.0'
    container_name: pgsql
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DATABASE: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '${FORDWARD_PGSQL_PORT}:5432'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - laravel
  adminer:
    build:
      context: .
      dockerfile: adminer-dockerfile
    container_name: adminer
    restart: always
    links:
      - pgsql
    depends_on:
      - pgsql
    ports:
      - '8080:8080'
    networks:
      - laravel
  laravel.project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "laravel.project"
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT}:8025'
    networks:
        - laravel
networks:
  laravel:
