version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
    networks:
      - laravel
  pgsql:
    image: 'postgres:14.0'
    container_name: pgsql
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DATABASE: '${PGSQL_DATABASE}'
      POSTGRES_USER: '${PGSQL_USER}'
      POSTGRES_PASSWORD: '${PGSQL_PASSWORD}'
    ports:
      - '${FORDWARD_PGSQL_PORT:-54329}:5432'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
        - laravel
networks:
  laravel:
