version: '3.0'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeserver
      - pgsql
    networks:
      - node
  pgsql:
    image: 'postgres:14.0'
    container_name: pgsql
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DATABASE: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '${FORDWARD_PGSQL_PORT}:5432'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - node
  adminer:
    build:
      context: .
      dockerfile: adminer-dockerfile
    container_name: adminer
    restart: always
    links:
      - pgsql
    depends_on:
      - pgsql
    ports:
      - '8080:8080'
    networks:
      - node
  nodeserver:
    image: "node:${NODE_VERSION}-bullseye"
    container_name: "nodeserver"
    working_dir: /home/node/app
    restart: always
    volumes:
      - ./src:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - node
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT}:8025'
    networks:
        - node
networks:
  node:
    #volumes:
    #  mongodb: {}
