version: '3.0'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeserver
      - mongodb
    networks:
      - node
  mongodb:
    image: 'mongo:5.0.3-focal'
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    ports:
      - '${FORDWARD_MONGO_PORT}:27017'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo:/data/mongo
    networks:
      - node
  adminer:
    build:
      context: .
      dockerfile: adminer-dockerfile
    container_name: adminer
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
    networks:
      - node
  nodeserver:
    image: "node:${NODE_VERSION}-bullseye"
    container_name: "nodeserver"
    working_dir: /home/node/app
    restart: always
    volumes:
      - ./src:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - node
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT}:8025'
    networks:
        - node
networks:
  node:
    #volumes:
    #  mongodb: {}
