version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel.project
      - mysql
    networks:
      - laravel
  mysql:
    image: 'mysql:5.6'
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${FORDWARD_MYSQL_PORT}:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  adminer:
    build:
      context: .
      dockerfile: adminer-dockerfile
    container_name: adminer
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    networks:
      - laravel
  laravel.project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'laravel.project'
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT}:8025'
    networks:
        - laravel
networks:
  laravel:
