version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel.project
      - mongodb
    networks:
      - laravel
  mongodb:
    image: 'mongo:5.0.3-focal'
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    ports:
      - '${FORDWARD_MONGO_PORT}:27017'
    volumes:
      - ./mongo:/etc/mongo
    networks:
      - laravel
  adminer:
    build:
      context: .
      dockerfile: adminer-dockerfile
    container_name: adminer
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
    networks:
      - laravel
  laravel.project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "laravel.project"
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT}:8025'
    networks:
        - laravel
networks:
  laravel:
    #volumes:
    #  mongodb: {}
